<?xml version ="1.0" encoding= "UTF-8"?>
<!DOCTYPE catalog [
<!ELEMENT catalog (articol*)>
<!ELEMENT articol (nume,categorie,descriere?)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT categorie (#PCDATA)>
<!ELEMENT descriere (#PCDATA)>
<!ATTLIST articol id CDATA #REQUIRED>
]>
<catalog>
    <articol id="1">
      <nume>Coca Cola</nume>
      <categorie>Bauturi</categorie>
    </articol>
    <articol id="2">
      <nume>Ciocolata</nume>
      <categorie>Alimente</categorie>
    </articol>
    <articol id="3">
      <nume>HP Pavilion</nume>
      <categorie>Laptopuri</categorie>
    </articol>
</catalog>